//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCR_Mst
    {
        public int DCRId { get; set; }
        public Nullable<int> WorkTypeId { get; set; }
        public string WorkWithIds { get; set; }
        public Nullable<long> TourId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> SubAreaId { get; set; }
        public string AreaNote { get; set; }
        public Nullable<bool> Tourvariance { get; set; }
        public Nullable<int> varianceAreaID { get; set; }
        public Nullable<int> varianceSubAreaID { get; set; }
        public string Latitude { get; set; }
        public string longitude { get; set; }
        public string TourPlanVariation { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string WorkWithUserId { get; set; }
    }
}
