//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorProductReport_Mst
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ReportId { get; set; }
        public Nullable<long> GrouptypeID { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> ProductCaseId { get; set; }
        public string ProductName { get; set; }
        public string CaseName { get; set; }
        public string RxType { get; set; }
        public string ValueType { get; set; }
        public string WeigtageType { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
