//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorReport_Mst
    {
        public int DoctorReportId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<long> DCRId { get; set; }
        public Nullable<int> ProductCaseId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string CaseName { get; set; }
        public string RxType { get; set; }
        public string Quantity { get; set; }
        public string ValueType { get; set; }
        public string WeigtageType { get; set; }
        public string VisitSection { get; set; }
        public string DiscussionPad { get; set; }
        public string Medicine { get; set; }
        public string Prescription { get; set; }
        public string PrescriptionText { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> MeetingTypeId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
    }
}
