//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Mst
    {
        public int DoctorId { get; set; }
        public string DoctorCode { get; set; }
        public string DoctorName { get; set; }
        public int GradeName { get; set; }
        public string Qualification { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string Add4 { get; set; }
        public string Pin { get; set; }
        public string PhoneNo { get; set; }
        public string RefrenceNo { get; set; }
        public string CategoryName { get; set; }
        public string SubAreaName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Dow { get; set; }
        public string Email { get; set; }
        public string FieldStaffName { get; set; }
        public string DivisionName { get; set; }
        public string DoctorClass { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int CreatedBy { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CertificateId { get; set; }
    }
}
