//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageBalloon
    {
        public long ManageBalloonID { get; set; }
        public Nullable<long> MasterUserID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> SubUserID { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
