//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCase_Mst
    {
        public int ProductCaseId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string CaseName { get; set; }
        public string Name { get; set; }
        public string MeasureIn { get; set; }
        public string StrangthIn { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PTS { get; set; }
        public string Pack { get; set; }
        public string PTR { get; set; }
        public string MRP { get; set; }
        public string STDRate { get; set; }
        public string BrandName { get; set; }
        public string ProductTypeId { get; set; }
    }
}
