//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionalReport_Mst
    {
        public int PromotionalReportId { get; set; }
        public Nullable<int> PromotionalId { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string WorkWithIds { get; set; }
        public string WorkWithUserId { get; set; }
        public Nullable<int> SubAreaId { get; set; }
        public string PromotionalImage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
