//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerReport_Mst
    {
        public int ReatailerReportId { get; set; }
        public Nullable<int> ReatailerId { get; set; }
        public Nullable<long> DCRId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<long> ProductCaseId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> SubAreaId { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string DiscussionPad { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CaseName { get; set; }
        public string Name { get; set; }
        public string MeasureIn { get; set; }
        public string StrangthIn { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
    }
}
