//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer_mst
    {
        public long ReatailerId { get; set; }
        public Nullable<int> Usertype { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string OfficePhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> GradeName { get; set; }
        public string Refrence { get; set; }
        public string ShortName { get; set; }
        public string RetailerCode { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int CreatedBy { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DivName { get; set; }
        public string SubArea { get; set; }
    }
}
