//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourAreaProgram_Mst
    {
        public long Id { get; set; }
        public Nullable<long> TourId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public string TourAreaCode { get; set; }
        public Nullable<long> SubAreaId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AreaName { get; set; }
        public string SubAreaName { get; set; }
    }
}
