//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker_Mst
    {
        public long TrackID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Lattitude { get; set; }
        public string longitude { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
