//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public long UID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Height { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
