//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metizsoft.Data.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public long UserInfoId { get; set; }
        public long MasterUserID { get; set; }
        public Nullable<long> SubUserID { get; set; }
        public string Name { get; set; }
        public string Weight { get; set; }
        public string BMI { get; set; }
        public string BodyFat { get; set; }
        public string BodyWater { get; set; }
        public string Bone { get; set; }
        public string VisceralFat { get; set; }
        public string BMR { get; set; }
        public string MuscleMass { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
